####################################################################
# This configuration is adapted from Damien Zufferey's PSync project
#            https://github.com/dzufferey/psync
####################################################################
os:
  - linux

language: scala

sudo: true

scala:
  - 2.12.5

jdk:
  - oraclejdk8
  
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test 
  - sudo apt-get update
  - sudo apt-get upgrade
  - sudo apt-get dist-upgrade
  - sudo apt-get install libstdc++6

install:
  - ./.ci/install_z3.sh

env:
  - PATH="$HOME/z3/z3-4.6.0-x64-ubuntu-16.04/bin/:$PATH"

before_script:
  - sudo chmod +x /usr/local/bin/sbt

script:
  - travis_wait 20 sbt ++$TRAVIS_SCALA_VERSION test

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/z3
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

